left_vacant_template_questions = [
    "Locate several points within the vacant space positioned to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate several spots within the vacant area situated to the left side of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find several locations within the vacant space to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate several points within the vacant space situated on the left part of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find a few locations in the blank space to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate several spots in the free space to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Identify a few places in the vacant region to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate several points within the vacant space situated on the left part of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Select a few points in the free space to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate some places in the vacant space to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Identify a few spots in the free region on the left part of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Pinpoint the vacant space that is to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Identify some points within the free space that is to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    

    "In the image, there is a [A]. Locate several points within the vacant space positioned to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Locate several spots within the vacant area situated to the left side of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find several locations within the vacant space to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Locate several points within the vacant space situated on the left part of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find a few locations in the blank space to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Locate several spots in the free space to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Identify a few places in the vacant region to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Locate several points within the vacant space situated on the left part of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Select a few points in the free space to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Locate some places in the vacant space to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Identify a few spots in the free region on the left part of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Pinpoint the vacant space that is to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Identify some points within the free space that is to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Pinpoint the vacant space that is to the left of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    
    # 衍生句式（新增）
    "Where is a free space to the left of [A]? Please provide its 2D coordinates.",
    "Can you find a vacant point to the left of [A]? Please provide its 2D coordinates.",
    "Can you point to a free location to the left of [A]? Please provide its 2D coordinates.",
    "Where can I find a free point to the left of [A]? Please provide its 2D coordinates.",
    "What is the location of a free spot to the left of [A]? Please provide its 2D coordinates.",
    "Give me the position of a free location to the left of [A]. Please provide its 2D coordinates.",
    "Choose a point to the left of [A] in the vacant region. Please provide its 2D coordinates.",
    "What is the 2D location of a free space to the left of [A]? Please provide its 2D coordinates.",
    
    # 更简洁指令式（无解释尾部，适合多模态训练）
    "Point to a free spot to the left of [A].",
    "Point to the vacant area to the left of [A] in the image.",
    "Point to any free space to the left of [A] in the image.",
    "Locate the blank area to the left of [A] in the image.",
    "Locate any vacant position to the left of [A] in the image.",
]

left_vacant_template_answers = ["[X]"]

right_vacant_template_questions = [
    "Locate several points within the vacant area that is situated to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate a few points within the vacant space to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Pinpoint several spots within the vacant area located to the right-hand side of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find a few locations in the empty space that is to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Identify some points in the unoccupied region to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate some spots to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find some places in the vacant space to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Pinpoint several spots in the vacant area that lies to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    
    "In the image, there is a [A]. Locate several points within the vacant area that is situated to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Locate a few points within the vacant space to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Pinpoint several spots within the vacant area located to the right-hand side of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find a few locations in the empty space that is to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Identify some points in the unoccupied region to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Locate some spots to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find some places in the vacant space to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Pinpoint several spots in the vacant area that lies to the right of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    
    "Where is a free space to the right of [A]? Please provide its 2D coordinates.",
    "Can you find a vacant point to the right of [A]? Please provide its 2D coordinates.",
    "Can you point to a free location to the right of [A]? Please provide its 2D coordinates.",
    "Where can I find a free point to the right of [A]? Please provide its 2D coordinates.",
    "What is the location of a free spot to the right of [A]? Please provide its 2D coordinates.",
    "Give me the position of a free location to the right of [A]. Please provide its 2D coordinates.",
    "Choose a point to the right of [A] in the vacant region. Please provide its 2D coordinates.",
    "What is the 2D location of a free space to the right of [A]? Please provide its 2D coordinates.",
    "Point to a free spot to the right of [A].",
    "Point to the vacant area to the right of [A] in the image.",
    "Locate any vacant space to the right of [A] in the image.",
]
right_vacant_template_answers = ["[X]"]

front_vacant_template_questions = [
    "Select one or more locations within the vacant area that is in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate several spots within the vacant area that is in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate several points within the vacant area that is in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Detect a few locations within the vacant space in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find several points in the free space in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find several spots in the free space in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate some spots within the free space in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find a few locations in the free space in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find some points within the space that is in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Locate a few points in the free space on the front side of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find a few points in the vacant space in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Locate some spots witihin the unoccupied area in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find several spots in the free space in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Locate some points within the free space in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Pinpoint several spots in the vacant area that lies in front of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",

    
    "Where is a free space in front of [A]? Please provide its 2D coordinates.",
    "Can you find a vacant space in front of [A]? Please provide its 2D coordinates.",
    "Can you point to a free location in front of [A]? Please provide its 2D coordinates.",
    "Where can I find a free point in front of [A]? Please provide its 2D coordinates.",
    "What is the location of a free spot in front of [A]? Please provide its 2D coordinates.",
    "Give me the position of a free location in front of [A]. Please provide its 2D coordinates.",
    "Choose a point in front of [A] from the vacant region. Please provide its 2D coordinates.",
    "What is the 2D location of a free space in front of [A]? Please provide its 2D coordinates.",
    "Point to a free spot in front of [A].",
    "Point to the vacant area in front of [A] in the image.",
    "Locate any vacant space in front of [A] in the image.",
]
front_vacant_template_answers = ["[X]"]

behind_vacant_template_questions = [
    "Locate a few spots within the unoccupied space behind [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find a few points in the vacant space behind [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find several locations within the vacant space behind [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find some points in the free space behind [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find a few places in the vacant space behind [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate several points within a vacant area on the back side of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Select a few points in the free space to the back side of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Pinpoint a few points in the free space to the back side of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    
    "In the image, there is a [A]. Locate a few spots within the unoccupied space behind [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find a few points in the vacant space behind [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find several locations within the vacant space behind [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find some points in the free space behind [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Find a few places in the vacant space behind [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Locate several points within a vacant area on the back side of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Select a few points in the free space to the back side of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Pinpoint a few points in the free space to the back side of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",

    
    
    "Where is a free space behind [A]? Please provide its 2D coordinates.",
    "Can you find a vacant location behind [A]? Please provide its 2D coordinates.",
    "Can you point to a free space behind [A]? Please provide its 2D coordinates.",
    "Where can I find a free point behind [A]? Please provide its 2D coordinates.",
    "What is the location of a free spot behind [A]? Please provide its 2D coordinates.",
    "Give me the position of a free point behind [A]. Please provide its 2D coordinates.",
    "Choose a point behind [A] in the unoccupied space. Please provide its 2D coordinates.",
    "What is the 2D location of a free area behind [A]? Please provide its 2D coordinates.",
    "Point to a free spot behind [A].",
    "Point to the vacant space behind [A] in the image.",
    "Locate the unoccupied area behind [A] in the image.",
]
behind_vacant_template_answers = ["[X]"]

above_vacant_template_questions = [
    "From a real-world perspective, locate several points in the blank space situated above [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "From a real-world perspective, locate several spots within the vacant space situated above [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "From a real-world perspective, find some spots in the free space above [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "From a real-world perspective, locate several points within the vacant area on top of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "From a real-world perspective, find a few locations in the empty space that is ontop of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "From a real-world perspective, Pinpoint a few locations in the empty space that is ontop of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",

    "In the image, there is a [A]. From a real-world perspective, locate several points in the blank space situated above [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. From a real-world perspective, locate several spots within the vacant space situated above [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. From a real-world perspective, find some spots in the free space above [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. From a real-world perspective, locate several points within the vacant area on top of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. From a real-world perspective, find a few locations in the empty space that is ontop of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. Pinpoint a few locations in the empty space that is ontop of [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",

    
    
    
    "From a real-world perspective, where is a free space above [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, can you find a vacant point above [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, can you point to a free location above [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, where can I find a free point above [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, what is the location of a free spot above [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, give me the position of a free point above [A]. Please provide its 2D coordinates.",
    "From a real-world perspective, choose a point above [A] in the vacant region. Please provide its 2D coordinates.",
    "From a real-world perspective, what is the 2D location of a free space above [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, point to a free spot above [A].",
    "From a real-world perspective, point to the free space above [A] in the image.",
    "From a real-world perspective, locate any blank space above [A] in the image.",
]
above_vacant_template_answers = ["[X]"]

below_vacant_template_questions = [
    "From a real-world perspective, locate several spots within the vacant area situated below [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "From a real-world perspective, locate several points within the vacant space in [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "From a real-world perspective, locate several spots within the free region under [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "From a real-world perspective, identify some places in the vacant space underneath [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "From a real-world perspective, identify some places in the vacant space underneath [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "From a real-world perspective, Pinpoint some places in the vacant space underneath [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",

    "In the image, there is a [A]. From a real-world perspective, locate several spots within the vacant area situated below [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. From a real-world perspective, locate several points within the vacant space in [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. From a real-world perspective, locate several spots within the free region under [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. From a real-world perspective, identify some places in the vacant space underneath [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. From a real-world perspective, identify some places in the vacant space underneath [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "In the image, there is a [A]. From a real-world perspective, Pinpoint some places in the vacant space underneath [A]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1)], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",

    
    "From a real-world perspective, where is a free space below [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, can you find a vacant location below [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, can you point to a free area below [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, where can I find a free point below [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, what is the location of a free spot below [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, give me the position of a free point below [A]. Please provide its 2D coordinates.",
    "From a real-world perspective, choose a point below [A] in the vacant region. Please provide its 2D coordinates.",
    "From a real-world perspective, what is the 2D location of a free space underneath [A]? Please provide its 2D coordinates.",
    "From a real-world perspective, point to a free spot below [A].",
    "From a real-world perspective, Point to the vacant region under [A] in the image.",
    "From a real-world perspective, locate the blank area beneath [A] in the image.",
]
below_vacant_template_answers = ["[X]"]

between_vacant_template_questions = [
    "Identify several spots within the vacant space that's between [A] and [B]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1), (x2, y2), ...], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate several points within the vacant area that lies between [A] and [B]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1), (x2, y2), ...], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate a few places in the free space between [A] and [B]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1), (x2, y2), ...], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Indicate several points within the vacant area that lies between [A] and [B]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1), (x2, y2), ...], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Locate some points within the free area in between [A] and [B]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1), (x2, y2), ...], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Identify some spots in the free space between [A] and [B]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1), (x2, y2), ...], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find several places in the vacant space in between [A] and [B]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1), (x2, y2), ...], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Find a few locations in the empty space that is in between [A] and [B]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1), (x2, y2), ...], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Pinpoint some spots within the free space that is in between [A] and [B]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1), (x2, y2), ...], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
    "Pinpoint some points within the vacant space that is in between [A] and [B]. Your answer should be formatted as a list of tuples, i.e. [(x1, y1), (x2, y2), ...], where each tuple contains the x and y coordinates of a point satisfying the conditions above. The coordinates should be between 0 and 1, indicating the normalized pixel locations of the points in the image.",
]

between_vacant_template_answers = ["[X]"]