TEMPLATES = {
    "left_to_right": [
        "{dense_caption}, which is the {ordinal} {class_name} from left to right",
        "{dense_caption}, which is the {ordinal} {class_name} in left-to-right order",
        "{dense_caption}, which appears as the {ordinal} {class_name} when viewed from the left",
        "{dense_caption}, which ranks as the {ordinal} {class_name} in left-to-right order",
        "{dense_caption}, which is counted as the {ordinal} {class_name}, starting from the left",
        "{dense_caption}, the {ordinal} {class_name} from the left",
        "{dense_caption}, the {ordinal} {class_name} in the left-to-right sequence",
        "{dense_caption}, the {ordinal} {class_name} viewed from the left",
        "{dense_caption}, the {ordinal} {class_name} when ordered from left to right",
        "{dense_caption}, the {ordinal} {class_name} positioned from the left",
        "{dense_caption}, placed as the {ordinal} {class_name} when sorted from left to right",
        "{dense_caption}, positioned as the {ordinal} {class_name} in left-to-right order",
        "{dense_caption}, acting as the {ordinal} {class_name} starting from the left",
        "{dense_caption}, arranged as the {ordinal} {class_name} when viewed from the left",
        "{dense_caption}, marked as the {ordinal} {class_name} in a left-to-right arrangement",
    ],
    "right_to_left": [
        "{dense_caption}, which is the {ordinal} {class_name} from right to left",
        "{dense_caption}, which is the {ordinal} {class_name} in right-to-left order",
        "{dense_caption}, which appears as the {ordinal} {class_name} when viewed from the right",
        "{dense_caption}, which ranks as the {ordinal} {class_name} in right-to-left order",
        "{dense_caption}, which is counted as the {ordinal} {class_name}, starting from the right",
        "{dense_caption}, the {ordinal} {class_name} from the right",
        "{dense_caption}, the {ordinal} {class_name} in the right-to-left sequence",
        "{dense_caption}, the {ordinal} {class_name} viewed from the right",
        "{dense_caption}, the {ordinal} {class_name} when ordered from right to left",
        "{dense_caption}, the {ordinal} {class_name} positioned from the right",
        "{dense_caption}, placed as the {ordinal} {class_name} when sorted from right to left",
        "{dense_caption}, positioned as the {ordinal} {class_name} in right-to-left order",
        "{dense_caption}, acting as the {ordinal} {class_name} starting from the right",
        "{dense_caption}, arranged as the {ordinal} {class_name} when viewed from the right",
        "{dense_caption}, marked as the {ordinal} {class_name} in a right-to-left arrangement"
    ],
    "front_to_back": [
        "{dense_caption}, which is the {ordinal} {class_name} from front to back",
        "{dense_caption}, which is the {ordinal} {class_name} in front-to-back order",
        "{dense_caption}, which appears as the {ordinal} {class_name} when viewed from the front",
        "{dense_caption}, which ranks as the {ordinal} {class_name} in front-to-back order",
        "{dense_caption}, which is counted as the {ordinal} {class_name}, starting from the front",
        "{dense_caption}, the {ordinal} {class_name} from the front",
        "{dense_caption}, the {ordinal} {class_name} in the front-to-back sequence",
        "{dense_caption}, the {ordinal} {class_name} viewed from the front",
        "{dense_caption}, the {ordinal} {class_name} when ordered from front to back",
        "{dense_caption}, the {ordinal} {class_name} positioned from the front",
        "{dense_caption}, placed as the {ordinal} {class_name} when sorted from front to back",
        "{dense_caption}, positioned as the {ordinal} {class_name} in front-to-back order",
        "{dense_caption}, acting as the {ordinal} {class_name} starting from the front",
        "{dense_caption}, arranged as the {ordinal} {class_name} when viewed from the front",
        "{dense_caption}, marked as the {ordinal} {class_name} in a front-to-back arrangement"
    ],
    "back_to_front": [
        "{dense_caption}, which is the {ordinal} {class_name} from back to front",
        "{dense_caption}, which is the {ordinal} {class_name} in back-to-front order",
        "{dense_caption}, which appears as the {ordinal} {class_name} when viewed from the back",
        "{dense_caption}, which ranks as the {ordinal} {class_name} in back-to-front order",
        "{dense_caption}, which is counted as the {ordinal} {class_name}, starting from the back",
        "{dense_caption}, the {ordinal} {class_name} from the back",
        "{dense_caption}, the {ordinal} {class_name} in the back-to-front sequence",
        "{dense_caption}, the {ordinal} {class_name} viewed from the back",
        "{dense_caption}, the {ordinal} {class_name} when ordered from back to front",
        "{dense_caption}, the {ordinal} {class_name} positioned from the back",
        "{dense_caption}, placed as the {ordinal} {class_name} when sorted from back to front",
        "{dense_caption}, positioned as the {ordinal} {class_name} in back-to-front order",
        "{dense_caption}, acting as the {ordinal} {class_name} starting from the back",
        "{dense_caption}, arranged as the {ordinal} {class_name} when viewed from the back",
        "{dense_caption}, marked as the {ordinal} {class_name} in a back-to-front arrangement"
    ],
    "top_to_bottom": [
        "{dense_caption}, which is the {ordinal} {class_name} from top to bottom",
        "{dense_caption}, which is the {ordinal} {class_name} in top-to-bottom order",
        "{dense_caption}, which appears as the {ordinal} {class_name} when viewed from the top",
        "{dense_caption}, which ranks as the {ordinal} {class_name} in top-to-bottom order",
        "{dense_caption}, which is counted as the {ordinal} {class_name}, starting from the top",
        "{dense_caption}, the {ordinal} {class_name} from the top",
        "{dense_caption}, the {ordinal} {class_name} in the top-to-bottom sequence",
        "{dense_caption}, the {ordinal} {class_name} viewed from the top",
        "{dense_caption}, the {ordinal} {class_name} when ordered from top to bottom",
        "{dense_caption}, the {ordinal} {class_name} positioned from the top",
        "{dense_caption}, placed as the {ordinal} {class_name} when sorted from top to bottom",
        "{dense_caption}, positioned as the {ordinal} {class_name} in top-to-bottom order",
        "{dense_caption}, acting as the {ordinal} {class_name} starting from the top",
        "{dense_caption}, arranged as the {ordinal} {class_name} when viewed from the top",
        "{dense_caption}, marked as the {ordinal} {class_name} in a top-to-bottom arrangement"
    ],
    "bottom_to_top": [
        "{dense_caption}, which is the {ordinal} {class_name} from bottom to top",
        "{dense_caption}, which is the {ordinal} {class_name} in bottom-to-top order",
        "{dense_caption}, which appears as the {ordinal} {class_name} when ordered from the bottom",
        "{dense_caption}, which ranks as the {ordinal} {class_name} in bottom-to-top order",
        "{dense_caption}, which is counted as the {ordinal} {class_name}, starting from the bottom",
        "{dense_caption}, the {ordinal} {class_name} from the bottom",
        "{dense_caption}, the {ordinal} {class_name} in the bottom-to-top sequence",
        "{dense_caption}, the {ordinal} {class_name} ordered from the bottom",
        "{dense_caption}, the {ordinal} {class_name} when ordered from bottom to top",
        "{dense_caption}, the {ordinal} {class_name} positioned from the bottom",
        "{dense_caption}, placed as the {ordinal} {class_name} when sorted from bottom to top",
        "{dense_caption}, positioned as the {ordinal} {class_name} in bottom-to-top order",
        "{dense_caption}, acting as the {ordinal} {class_name} starting from the bottom",
        "{dense_caption}, arranged as the {ordinal} {class_name} when ordered from the bottom",
        "{dense_caption}, marked as the {ordinal} {class_name} in a bottom-to-top arrangement"
    ]
}

ORDINALS = {
    1: "first", 2: "second", 3: "third", 4: "fourth",
    5: "fifth", 6: "sixth", 7: "seventh", 8: "eighth",
    9: "ninth", 10: "tenth", 11: "eleventh", 12: "twelfth",
    13: "thirteenth", 14: "fourteenth", 15: "fifteenth",
    16: "sixteenth", 17: "seventeenth", 18: "eighteenth",
    19: "nineteenth", 20: "twentieth"
}